"""added country and zipcode to model

Revision ID: 356f6f02db61
Revises: 848f2f811ff5
Create Date: 2021-05-31 14:40:25.287851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '356f6f02db61'
down_revision = '848f2f811ff5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('counts', sa.Column('country', sa.String(length=50), nullable=False))
    op.add_column('counts', sa.Column('zipcode', sa.String(length=6), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('counts', 'zipcode')
    op.drop_column('counts', 'country')
    # ### end Alembic commands ###
